stages:
  - pre
  - test


build_rmbt:
  stage: pre
  image: gcc
  script:
    - apt-get update
    - apt-get install -y libjson-c-dev
    - git clone https://github.com/lwimmer/rmbt-client
    - cd rmbt-client && ./autobuild.sh && cd ..
    - mv rmbt-client/src/rmbt rmbt
  artifacts:
    paths:
      - rmbt

simple_test:
  dependencies:
    - build_rmbt
  image: python:3-slim
  stage: test
  script:
    - apt-get update
    - apt-get install -y iputils-ping libjson-c-dev xz-utils
    - cp $(find / -name "rmbt") /bin/rmbt

    - python -m netmetr --help
    - python -m netmetr --debug --control-server netmetr-control.labs.nic.cz --no-run 2>&1 | tee log.out && echo -e "\nExtracted errors:" && if grep "ERROR" log.out; then exit 1; else exit 0; fi


linters:
  stage: test
  # originally archlinux, that somehow broke. Debian testing should be pretty recent as well.
  image: debian:testing
  before_script:
    - apt-get update && apt-get install --no-install-recommends --no-install-suggests -y python3 mypy bandit flake8 && apt-get clean -y && rm -rf /var/lib/apt/lists/*
  script:
    - mypy netmetr/
    - bandit -r netmetr/
    - flake8 --max-line-length 120 netmetr/
